import type { Card } from './index.js';

export const cards: Record<string, Partial<Card>> = {
  "Oil 3": {
    cost: 3,
    resourceType: 'oil',
    resources: 2,
    power: 1,
  },
  "Oil 7": {
    cost: 7,
    resourceType: 'oil',
    resources: 3,
    power: 2,
  },
  "Oil 9": {
    cost: 9,
    resourceType: 'oil',
    resources: 1,
    power: 1,
  },
  "Oil 16": {
    cost: 16,
    resourceType: 'oil',
    resources: 2,
    power: 3,
  },
  "Oil 26": {
    cost: 26,
    resourceType: 'oil',
    resources: 2,
    power: 5,
  },
  "Oil 32": {
    cost: 32,
    resourceType: 'oil',
    resources: 3,
    power: 6,
  },
  "Oil 35": {
    cost: 35,
    resourceType: 'oil',
    resources: 1,
    power: 5,
  },
  "Oil 40": {
    cost: 40,
    resourceType: 'oil',
    resources: 2,
    power: 6,
  },
  "Clean 50": {
    cost: 50,
    resourceType: 'clean',
    resources: 0,
    power: 6,
  },
  "Coal 4": {
    cost: 4,
    resourceType: 'coal',
    resources: 2,
    power: 1,
  },
  "Coal 8": {
    cost: 8,
    resourceType: 'coal',
    resources: 3,
    power: 2,
  },
  "Coal 10": {
    cost: 10,
    resourceType: 'coal',
    resources: 2,
    power: 2,
  },
  "Coal 15": {
    cost: 15,
    resourceType: 'coal',
    resources: 2,
    power: 3,
  },
  "Coal 20": {
    cost: 20,
    resourceType: 'coal',
    resources: 3,
    power: 5,
  },
  "Coal 25": {
    cost: 25,
    resourceType: 'coal',
    resources: 2,
    power: 5,
  },
  "Coal 31": {
    cost: 31,
    resourceType: 'coal',
    resources: 3,
    power: 6,
  },
  "Coal 36": {
    cost: 36,
    resourceType: 'coal',
    resources: 3,
    power: 7,
  },
  "Coal 42": {
    cost: 42,
    resourceType: 'coal',
    resources: 2,
    power: 6,
  },
  "Garbage 6": {
    cost: 6,
    resourceType: 'garbage',
    resources: 1,
    power: 1,
  },
  "Garbage 14": {
    cost: 14,
    resourceType: 'garbage',
    resources: 2,
    power: 2,
  },
  "Garbage 19": {
    cost: 19,
    resourceType: 'garbage',
    resources: 2,
    power: 3,
  },
  "Garbage 24": {
    cost: 24,
    resourceType: 'garbage',
    resources: 2,
    power: 4,
  },
  "Garbage 30": {
    cost: 30,
    resourceType: 'garbage',
    resources: 3,
    power: 6,
  },
  "Garbage 38": {
    cost: 38,
    resourceType: 'garbage',
    resources: 3,
    power: 7,
  },
  "Hybrid 5": {
    cost: 5,
    resourceType: 'hybrid',
    resources: 2,
    power: 1,
  },
  "Hybrid 12": {
    cost: 12,
    resourceType: 'hybrid',
    resources: 2,
    power: 2,
  },
  "Hybrid 29": {
    cost: 29,
    resourceType: 'hybrid',
    resources: 1,
    power: 4,
  },
  "Hybrid 46": {
    cost: 46,
    resourceType: 'hybrid',
    resources: 3,
    power: 7,
  },
  "Hybrid 21": {
    cost: 21,
    resourceType: 'hybrid',
    resources: 2,
    power: 4,
  },
  "Nuclear 11": {
    cost: 11,
    resourceType: 'uranium',
    resources: 1,
    power: 2,
  },
  "Nuclear 17": {
    cost: 17,
    resourceType: 'uranium',
    resources: 1,
    power: 2,
  },
  "Nuclear 23": {
    cost: 23,
    resourceType: 'uranium',
    resources: 1,
    power: 3,
  },
  "Nuclear 28": {
    cost: 28,
    resourceType: 'uranium',
    resources: 1,
    power: 4,
  },
  "Nuclear 34": {
    cost: 34,
    resourceType: 'uranium',
    resources: 1,
    power: 5,
  },
  "Nuclear 39": {
    cost: 39,
    resourceType: 'uranium',
    resources: 1,
    power: 6,
  },
  "step-3": {
    cost: 99
  },
  "Wind 13": {
    cost: 13,
    resourceType: 'clean',
    resources: 0,
    power: 1,
  },
  "Wind 18": {
    cost: 18,
    resourceType: 'clean',
    resources: 0,
    power: 2,
  },
  "Wind 22": {
    cost: 22,
    resourceType: 'clean',
    resources: 0,
    power: 2,
  },
  "Wind 27": {
    cost: 27,
    resourceType: 'clean',
    resources: 0,
    power: 3,
  },
  "Wind 33": {
    cost: 33,
    resourceType: 'clean',
    resources: 0,
    power: 4,
  },
  "Wind 37": {
    cost: 37,
    resourceType: 'clean',
    resources: 0,
    power: 4,
  },
  "Wind 44": {
    cost: 44,
    resourceType: 'clean',
    resources: 0,
    power: 5,
  },
};
